### ISSUE TITLE
Create general functions for 5-min and 15-min binning

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_pgutils#2]
Create functions that take a specific timestamp and return the corresponding timestamp for that time bin:

`CREATE FUNCTION bin_5min (ts timestamp)`

`CREATE FUNCTION bin_15min (ts timestamp)`

**Comment by radumas** [comment]
Per @aharpalaniTO comment https://github.com/CityofToronto/bdit_pgutils/commit/65ab551fae062546071c03b263ad5539c66ac14d#commitcomment-33637542

>. Can we add optional parameters to this at some point to account for the following:
>
>1. the potential need to "round up" rather than "round down" to a bin (i.e. 5:14 -> 5:15 and not 5:10)
>2. a lag parameter, in seconds. For example for Bluetooth data, I believe the 5:10 time_bin is everything from 5:10:01 to 5:15:00?

1. Rounding is feasible, would need some further thought than using integer division
2. Couldn't the user do `public.datetime_bin(timestamp_val + lag, 15)` to incorporate a lag? ?

**Comment by aharpalaniTO** [comment]
good point re: 2. Agreed

**Comment by candu** [comment]
@radumas @aharpalaniTO you can mimic `round()`, `ceil()` using integer addition / division.  I'm not super-familiar with PL/SQL, but here are some Python examples:

```python
# assuming timestamp_val, bin_seconds are integers, this...
round(timestamp_val / bin_seconds)

# ...is equivalent to:
(timestamp_val + bin_seconds // 2) // bin_seconds

# ...and this...
ceil(timestamp_val / bin_seconds)

# ...is equivalent to:
(timestamp_val + bin_seconds - 1) // bin_seconds
```
